name: Self-hosted Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DenverCoder1/github-readme-streak-stats@main
        with:
          username: sunnyv-in
          theme: synthwave
          hide_border: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
